FROM ubuntu:rolling
RUN apt-get update && apt-get upgrade -y
RUN apt-get install sudo -y
RUN echo "deb https://deb.torproject.org/torproject.org bionic main" >> /etc/apt/sources.list
RUN echo "deb-src https://deb.torproject.org/torproject.org bionic main" >> /etc/apt/sources.list
RUN sudo apt-get install curl -y
RUN sudo apt-get install gnupg -y
RUN curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
RUN gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -
RUN apt update
RUN apt install -y tor deb.torproject.org-keyring
RUN echo "HiddenServiceDir /var/lib/tor/hidden_service/" >> /etc/tor/torrc
RUN echo "HiddenServicePort 9090 127.0.0.1:9090" >> /etc/tor/torrc
RUN echo "HiddenServiceVersion 3" >> /etc/tor/torrc
RUN sudo apt-get install inspircd -y
RUN sudo apt-get install python python-pip python-openssl openjdk-8-jre-headless git -y
RUN git clone https://github.com/qwebirc/qwebirc.git qwebirc
RUN pip install -r /qwebirc/requirements.txt
RUN cp /qwebirc/config.py.example /qwebirc/config.py
RUN sed -i 's/IRCSERVER, IRCPORT = "irc.myserver.com", 6667/IRCSERVER, IRCPORT = "127.0.0.1", 6667/' /qwebirc/config.py
RUN chmod +x ./qwebirc/compile.py
RUN python ./qwebirc/compile.py
RUN chmod +x ./qwebirc/run.py
RUN python ./qwebirc/run.py
RUN tor --runasdaemon 1
RUN cat /var/lib/tor/hidden_service/hostname
ENTRYPOINT python /qwebirc/run.py & tor
