FROM ubuntu:rolling
RUN apt-get update && apt-get upgrade -y
RUN apt-get install sudo curl -y
RUN echo "deb [trusted=yes] http://http.kali.org/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list
RUN apt-get install git live-build cdebootstrap -y
RUN git clone git://git.kali.org/live-build-config.git
RUN cd live-build-config && ./build.sh --distribution kali-rolling --verbose
