FROM ubuntu:rolling
RUN apt-get update && apt-get upgrade -y
RUN apt-get install sudo -y
RUN echo "deb https://deb.torproject.org/torproject.org bionic main" >> /etc/apt/sources.list
RUN echo "deb-src https://deb.torproject.org/torproject.org bionic main" >> /etc/apt/sources.list
RUN sudo apt-get install curl -y
RUN sudo apt-get install gnupg -y
RUN curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
RUN gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -
RUN apt update
RUN apt install -y tor deb.torproject.org-keyring
RUN echo "deb http://deb.torproject.org/torproject.org obfs4proxy main" >> /etc/apt/sources.list
RUN apt update
RUN sudo apt-get install obfs4proxy
RUN echo "#Bridge config" >> /etc/tor/torrc
RUN echo "RunAsDaemon 0" >> /etc/tor/torrc
RUN echo "ORPort 9003" >> /etc/tor/torrc
RUN echo "BridgeRelay 1" >> /etc/tor/torrc
RUN echo "ServerTransportPlugin obfs4 exec /usr/bin/obfs4proxy" >> /etc/tor/torrc
RUN echo "ServerTransportListenAddr obfs4 0.0.0.0:9004" >> /etc/tor/torrc
RUN echo "ExtORPort auto" >> /etc/tor/torrc
RUN echo "ContactInfo torworld" >> /etc/tor/torrc
RUN echo "Nickname torworld" >> /etc/tor/torrc
RUN tor --runasdaemon 1
RUN cat /etc/tor/pt_state/obfs4_bridgeline.txt
EXPOSE 9003 9004
ENTRYPOINT cat /etc/tor/pt_state/obfs4_bridgeline.txt & tor
